#!/usr/bin/env bash
# claude-master — cut-over from the legacy scripts of THIS workstation (author tooling, not
# shipped): plan §9.2. Every file touched is copied first into
#   ~/.claude/claude-master-legacy-<date>/   with a generated rollback.sh that puts it all back.
#
#   bash cutover.sh              prints the plan (dry-run, default)
#   bash cutover.sh --yes        does it
#
# Steps (one function each): preflight, backup (+ rollback.sh), bashrc, tmuxconf, settings,
# config, crontab, legacy_away, sessions_link. Values like ~/.claude-pixel or the script names
# are THIS machine's legacy: they are allowed here and nowhere in the plugin (D3).
#
# Test hooks: CM_HOME (fake home), CM_BIN (claude-master dispatcher), CM_CRONTAB_CMD,
# CM_SKIP_DOCTOR=1, CLAUDE_MASTER_CONFIG.
set -euo pipefail
if [ -n "${CM_TRACE:-}" ]; then set -x; fi

YES=0
for a in "$@"; do
  case "$a" in
    --yes|--si) YES=1 ;;
    --dry-run|--prova) YES=0 ;;
    *) echo "usage: bash cutover.sh [--yes|--dry-run]"; exit 2 ;;
  esac
done
H="${CM_HOME:-$HOME}"
CM="${CM_BIN:-$H/.local/bin/claude-master}"
CRONTAB="${CM_CRONTAB_CMD:-crontab}"
CFG="${CLAUDE_MASTER_CONFIG:-$H/.config/claude-master/config.json}"
STAMP="$(date +%Y%m%d-%H%M)"
BK="$H/.claude/claude-master-legacy-$STAMP"
LEGACY_SKILL="$H/.claude/skills/nuova-sessione"
LEGACY_BIN=(affianca attacca colore-sessione unisci sposta riaffianca)
SETTINGS=("$H/.claude/settings.json" "$H/.claude-pixel/settings.json")
BASHRC_START='^# Ripristino dopo un riavvio'
BASHRC_END='^# <<< claude-pixel <<<'

say() { printf '%s\n' "$*"; }
plan() { say "  [$1] $2"; }
do_or_plan() { # step, description, command...
  local step="$1" what="$2"; shift 2
  if [ "$YES" = 1 ]; then say "  [$step] $what"; "$@"; else plan "$step" "$what"; fi
}

preflight() {
  say "== preflight"
  [ -x "$CM" ] || { say "FAIL: $CM missing or not executable (run: claude-master init --shim)"; exit 1; }
  [ -f "$CFG" ] || { say "FAIL: config $CFG missing (run: claude-master init --yes)"; exit 1; }
  if [ "${CM_SKIP_DOCTOR:-0}" != 1 ]; then
    "$CM" doctor >/tmp/cm-cutover-doctor.$$ 2>&1 || { cat /tmp/cm-cutover-doctor.$$; say "FAIL: doctor has a FAIL line"; exit 1; }
    rm -f /tmp/cm-cutover-doctor.$$
  fi
  grep -q "$BASHRC_START" "$H/.bashrc" && grep -q "$BASHRC_END" "$H/.bashrc" \
    || { say "FAIL: .bashrc anchors not found ($BASHRC_START … $BASHRC_END): nothing touched"; exit 1; }
  grep -q 'claude-master/shell.sh' "$H/.bashrc" \
    || { say "FAIL: .bashrc has no 'source ~/.config/claude-master/shell.sh' line (claude-master init --shell)"; exit 1; }
  [ -d "$BK" ] && { say "FAIL: $BK already exists"; exit 1; }
  say "  ok: shim, config, .bashrc anchors, backup folder free"
}

backup() {
  say "== backup → $BK"
  if [ "$YES" != 1 ]; then
    plan backup "copy: $LEGACY_SKILL, ${LEGACY_BIN[*]}, .bashrc, .tmux.conf, ${SETTINGS[*]}, crontab, $CFG, ~/.claude-pixel/sessions"
    plan backup "write $BK/rollback.sh"
    return
  fi
  mkdir -p "$BK/skills" "$BK/bin" "$BK/settings/claude" "$BK/settings/claude-pixel"
  [ -d "$LEGACY_SKILL" ] && cp -a "$LEGACY_SKILL" "$BK/skills/"
  for b in "${LEGACY_BIN[@]}"; do [ -e "$H/.local/bin/$b" ] && cp -a "$H/.local/bin/$b" "$BK/bin/"; done
  cp -a "$H/.bashrc" "$BK/bashrc"
  [ -f "$H/.tmux.conf" ] && cp -a "$H/.tmux.conf" "$BK/tmux.conf"
  [ -f "${SETTINGS[0]}" ] && cp -a "${SETTINGS[0]}" "$BK/settings/claude/settings.json"
  [ -f "${SETTINGS[1]}" ] && cp -a "${SETTINGS[1]}" "$BK/settings/claude-pixel/settings.json"
  "$CRONTAB" -l > "$BK/crontab.txt" 2>/dev/null || : > "$BK/crontab.txt"
  cp -a "$CFG" "$BK/config.json"
  [ -d "$H/.claude-pixel/sessions" ] && [ ! -L "$H/.claude-pixel/sessions" ] && cp -a "$H/.claude-pixel/sessions" "$BK/sessions-pixel"
  cat > "$BK/rollback.sh" <<EOF
#!/usr/bin/env bash
# Generated by cutover.sh on $STAMP: puts the legacy setup back, byte for byte.
set -euo pipefail
H="$H"; BK="$BK"; CRONTAB="\${CM_CRONTAB_CMD:-$CRONTAB}"
cp -a "\$BK/bashrc" "\$H/.bashrc"
[ -f "\$BK/tmux.conf" ] && cp -a "\$BK/tmux.conf" "\$H/.tmux.conf"
[ -f "\$BK/settings/claude/settings.json" ] && cp -a "\$BK/settings/claude/settings.json" "$H/.claude/settings.json"
[ -f "\$BK/settings/claude-pixel/settings.json" ] && cp -a "\$BK/settings/claude-pixel/settings.json" "$H/.claude-pixel/settings.json"
cp -a "\$BK/config.json" "$CFG"
"\$CRONTAB" "\$BK/crontab.txt"
[ -d "\$BK/skills/nuova-sessione" ] && { rm -rf "$LEGACY_SKILL"; mkdir -p "$(dirname "$LEGACY_SKILL")"; cp -a "\$BK/skills/nuova-sessione" "$LEGACY_SKILL"; }
for b in ${LEGACY_BIN[*]}; do [ -e "\$BK/bin/\$b" ] && cp -a "\$BK/bin/\$b" "$H/.local/bin/\$b"; done
if [ -L "$H/.claude-pixel/sessions" ]; then rm "$H/.claude-pixel/sessions"; [ -d "\$BK/sessions-pixel" ] && cp -a "\$BK/sessions-pixel" "$H/.claude-pixel/sessions"; fi
echo "rollback done: legacy setup restored from \$BK (open a new shell; live sessions of the second account need a restart)"
EOF
  chmod +x "$BK/rollback.sh"
  say "  backup written, rollback: bash $BK/rollback.sh"
}

bashrc() {
  say "== .bashrc: remove the legacy segment ($BASHRC_START … $BASHRC_END), keep the claude-master block"
  [ "$YES" = 1 ] || { plan bashrc "rewrite $H/.bashrc"; return; }
  python3 - "$H/.bashrc" "$BASHRC_START" "$BASHRC_END" <<'PY'
import re, sys
path, start, end = sys.argv[1], sys.argv[2].lstrip("^"), sys.argv[3].lstrip("^")
lines = open(path).read().split("\n")
i = next(n for n, l in enumerate(lines) if l.startswith(start))
j = next(n for n, l in enumerate(lines) if l.startswith(end))
assert i < j, "anchors in the wrong order"
out = lines[:i] + lines[j + 1:]
# no two blank lines in a row where the segment was
text = re.sub(r"\n{3,}", "\n\n", "\n".join(out))
open(path, "w").write(text)
print(f"  removed lines {i + 1}-{j + 1}")
PY
}

tmuxconf() {
  say "== .tmux.conf: mouse + status off + the claude-master block (init --tmux)"
  [ "$YES" = 1 ] || { plan tmuxconf "rewrite $H/.tmux.conf"; return; }
  {
    echo "set -g mouse on"
    echo "set -g status off"
    echo
    "$CM" init --tmux | tail -n +2
  } > "$H/.tmux.conf.cutover"
  mv "$H/.tmux.conf.cutover" "$H/.tmux.conf"
  say "  written; reload with: tmux source-file ~/.tmux.conf"
}

settings() {
  say "== settings: drop the legacy local-time hook (UserPromptSubmit) and any Stop hook pointing at riavvia.sh"
  for s in "${SETTINGS[@]}"; do
    [ -f "$s" ] || continue
    [ "$YES" = 1 ] || { plan settings "edit $s"; continue; }
    python3 - "$s" <<'PY'
import json, sys
p = sys.argv[1]
d = json.load(open(p))
h = d.get("hooks", {})
def keep(entry, needles):
    return not any(n in json.dumps(entry, ensure_ascii=False) for n in needles)
if "UserPromptSubmit" in h:
    h["UserPromptSubmit"] = [e for e in h["UserPromptSubmit"] if keep(e, ["[ora locale]", "[local time]"])]
    if not h["UserPromptSubmit"]:
        del h["UserPromptSubmit"]
if "Stop" in h:
    h["Stop"] = [e for e in h["Stop"] if keep(e, ["riavvia.sh"])]
    if not h["Stop"]:
        del h["Stop"]
if not h:
    d.pop("hooks", None)
json.dump(d, open(p, "w"), indent=2, ensure_ascii=False)
open(p, "a").write("\n")
print(f"  {p}: hooks now {sorted(h)}")
PY
  done
}

config() {
  say "== config: shell.wrappers = the real commands of each account, shell.restore_prompt = true"
  [ "$YES" = 1 ] || { plan config "edit $CFG (backup $CFG.bak-cutover)"; return; }
  cp -a "$CFG" "$CFG.bak-cutover"
  python3 - "$CFG" <<'PY'
import json, sys
p = sys.argv[1]
d = json.load(open(p))
acc = d.get("accounts", {})
d.setdefault("shell", {})["wrappers"] = {a.get("shell_command") or n: n for n, a in acc.items()}
d["shell"]["restore_prompt"] = True
json.dump(d, open(p, "w"), indent=2, ensure_ascii=False)
open(p, "a").write("\n")
print(f"  wrappers: {d['shell']['wrappers']}")
PY
}

crontab_step() {
  say "== crontab: registro.sh out, claude-master registry in"
  [ "$YES" = 1 ] || { plan crontab "remove the nuova-sessione/registro.sh line; claude-master init --cron --yes"; return; }
  # read first, write after: a `crontab -l | … | crontab -` pipeline races on the spool file
  # (the fake crontab of the tests lost that race once, 09/09 22:55); an empty result is fine
  current="$("$CRONTAB" -l 2>/dev/null || true)"
  printf '%s\n' "$current" | { grep -v 'nuova-sessione/registro.sh' || true; } | "$CRONTAB" -
  "$CM" init --cron --yes
}

legacy_away() {
  say "== legacy scripts: skill and ${LEGACY_BIN[*]} moved into the backup"
  [ "$YES" = 1 ] || { plan legacy "mv $LEGACY_SKILL and the scripts (backup already holds a copy)"; return; }
  [ -d "$LEGACY_SKILL" ] && rm -rf "$LEGACY_SKILL"
  for b in "${LEGACY_BIN[@]}"; do rm -f "$H/.local/bin/$b"; done
  say "  moved"
}

sessions_link() {
  say "== peer registry shared: ~/.claude-pixel/sessions → ~/.claude/sessions (E1)"
  if [ -L "$H/.claude-pixel/sessions" ]; then say "  already a symlink"; return; fi
  [ -d "$H/.claude/sessions" ] || { say "  skipped: $H/.claude/sessions missing"; return; }
  [ "$YES" = 1 ] || { plan sessions "replace the folder with a symlink (copy kept in the backup)"; return; }
  rm -rf "$H/.claude-pixel/sessions"
  ln -s "$H/.claude/sessions" "$H/.claude-pixel/sessions"
  say "  linked — live sessions of the second account must be restarted to register here"
}

preflight
backup
bashrc
tmuxconf
settings
config
crontab_step
legacy_away
sessions_link
echo
if [ "$YES" = 1 ]; then
  say "CUT-OVER DONE. Now: open a NEW shell, tmux source-file ~/.tmux.conf, one session per account with claude-master launch, then checklist §9.1."
  say "Anything red → bash $BK/rollback.sh"
else
  say "dry-run: nothing touched. Run with --yes to execute (backup + rollback.sh in $BK)."
fi
